version: '3.7'

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Should be port if the local machine needs to get at it,
    #  but should be expose if the flask container needs to get at it.
    expose:
      - "5432"
    # usually, you use the form:
    #environment:
    #  - VALUE:value
    # to set an environment variable, but for some reason with postgres users,
    # you NEED to do it this way: (not sure why. . .)
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: guess_me
      POSTGRES_DB: flask_db

volumes:
  postgres_data:
